export const PIECE_PAWN = 'pawn'
export const PIECE_KNIGHT = 'knight'
export const PIECE_BISHOP = 'bishop'
export const PIECE_ROOK = 'rook'
export const PIECE_QUEEN = 'queen'
export const PIECE_KING = 'king'
