export const DIFFICULTY_HARD = 'hard'
export const DIFFICULTY_MODERATE = 'moderate'
export const DIFFICULTY_EASY = 'easy'

export const DIFFICULTY_ORDER = [
  DIFFICULTY_EASY,
  DIFFICULTY_MODERATE,
  DIFFICULTY_HARD,
]

export const DAY_1 = '2023-10-27'

export const IDLE_ANIMATE_PATTERN_1 = [
  [{row: 3, column: 3}],
  [{row: 3, column: 4}],
  [{row: 4, column: 4}],
  [{row: 4, column: 3}],
  [{row: 4, column: 2}],
  [{row: 3, column: 2}],
  [{row: 2, column: 2}],
  [{row: 2, column: 3}],
  [{row: 2, column: 4}],
  [{row: 2, column: 5}],
  [{row: 3, column: 5}],
  [{row: 4, column: 5}],
  [{row: 5, column: 5}],
  [{row: 5, column: 4}],
  [{row: 5, column: 3}],
  [{row: 5, column: 2}],
  [{row: 5, column: 1}],
  [{row: 4, column: 1}],
  [{row: 3, column: 1}],
  [{row: 2, column: 1}],
  [{row: 1, column: 1}],
  [{row: 1, column: 2}],
  [{row: 1, column: 3}],
  [{row: 1, column: 4}],
  [{row: 1, column: 5}],
  [{row: 1, column: 6}],
  [{row: 2, column: 6}],
  [{row: 3, column: 6}],
  [{row: 4, column: 6}],
  [{row: 5, column: 6}],
  [{row: 6, column: 6}],
  [{row: 6, column: 5}],
  [{row: 6, column: 4}],
  [{row: 6, column: 3}],
  [{row: 6, column: 2}],
  [{row: 6, column: 1}],
  [{row: 6, column: 0}],
  [{row: 5, column: 0}],
  [{row: 4, column: 0}],
  [{row: 3, column: 0}],
  [{row: 2, column: 0}],
  [{row: 1, column: 0}],
  [{row: 0, column: 0}],
  [{row: 0, column: 1}],
  [{row: 0, column: 2}],
  [{row: 0, column: 3}],
  [{row: 0, column: 4}],
  [{row: 0, column: 5}],
  [{row: 0, column: 6}],
  [{row: 0, column: 7}],
  [{row: 1, column: 7}],
  [{row: 2, column: 7}],
  [{row: 3, column: 7}],
  [{row: 4, column: 7}],
  [{row: 5, column: 7}],
  [{row: 6, column: 7}],
  [{row: 7, column: 7}],
  [{row: 7, column: 6}],
  [{row: 7, column: 5}],
  [{row: 7, column: 4}],
  [{row: 7, column: 3}],
  [{row: 7, column: 2}],
  [{row: 7, column: 1}],
  [{row: 7, column: 0}],
]

export const IDLE_ANIMATE_PATTERN_2 = [
  [
    {row: 3, column: 3},
    {row: 3, column: 4},
    {row: 4, column: 4},
    {row: 4, column: 3},
  ],
  [],
  [
    {row: 2, column: 2},
    {row: 2, column: 3},
    {row: 2, column: 4},
    {row: 2, column: 5},
    {row: 3, column: 5},
    {row: 4, column: 5},
    {row: 5, column: 5},
    {row: 5, column: 4},
    {row: 5, column: 3},
    {row: 5, column: 2},
    {row: 4, column: 2},
    {row: 3, column: 2},
  ],
  [],
  [
    {row: 1, column: 1},
    {row: 1, column: 2},
    {row: 1, column: 3},
    {row: 1, column: 4},
    {row: 1, column: 5},
    {row: 1, column: 6},
    {row: 2, column: 6},
    {row: 3, column: 6},
    {row: 4, column: 6},
    {row: 5, column: 6},
    {row: 6, column: 6},
    {row: 6, column: 5},
    {row: 6, column: 4},
    {row: 6, column: 3},
    {row: 6, column: 2},
    {row: 6, column: 1},
    {row: 5, column: 1},
    {row: 4, column: 1},
    {row: 3, column: 1},
    {row: 2, column: 1},
  ],
  [],
  [
    {row: 0, column: 0},
    {row: 0, column: 1},
    {row: 0, column: 2},
    {row: 0, column: 3},
    {row: 0, column: 4},
    {row: 0, column: 5},
    {row: 0, column: 6},
    {row: 0, column: 7},
    {row: 1, column: 7},
    {row: 2, column: 7},
    {row: 3, column: 7},
    {row: 4, column: 7},
    {row: 5, column: 7},
    {row: 6, column: 7},
    {row: 7, column: 7},
    {row: 7, column: 6},
    {row: 7, column: 5},
    {row: 7, column: 4},
    {row: 7, column: 3},
    {row: 7, column: 2},
    {row: 7, column: 1},
    {row: 7, column: 0},
    {row: 6, column: 0},
    {row: 5, column: 0},
    {row: 4, column: 0},
    {row: 3, column: 0},
    {row: 2, column: 0},
    {row: 1, column: 0},
  ],
]

export const IDLE_ANIMATE_PATTERN_FINAL = [
  ...IDLE_ANIMATE_PATTERN_1,
  ...IDLE_ANIMATE_PATTERN_2,
]
